FROM node:20.4.0-alpine as builder

ARG DB_HOST
ENV DB_HOST=$DB_HOST

ARG DB_PORT
ENV DB_PORT=$DB_PORT

ARG POSTGRES_USER
ENV POSTGRES_USER=$POSTGRES_USER

ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD

ARG DB_NAME
ENV DB_NAME=$DB_NAME

ARG CLIENT_ORIGIN
ENV CLIENT_ORIGIN=$CLIENT_ORIGIN

COPY . /app
WORKDIR /app
RUN npm ci

CMD [ "npm", "run", "start:prod" ]