volumes:
  pg-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./pg-data
  pgadmin-data:

services:
  postgres:
    image: postgres:16
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .db.env
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dahakalab@gmail.com
    env_file:
      - .db.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  cache:
    image: redis/redis-stack-server:latest
    container_name: cache
    restart: always
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - "REDIS_ARGS=--enable-debug-command yes --enable-module-command yes"
    env_file:
      - .env