name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: dahakalab/cosmetology-backend:latest
      - name: Stop Docker container
        run: docker stop cosmetology-server
        shell: bash
      - name: Pull Docker img
        run: docker image pull dahakalab/cosmetology-backend:latest
        shell: bash
      - name: Start Docker img
        run: docker run -d --rm --name cosmetology-server-p 3000:3000 dahakalab/cosmetology-backend:latest
        shell: bash