name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/template/build
      - name: Lint
        run: npm run lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/template/build
      - name: Test
        run: npm run test