name: Lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use node
        uses: actions/setup-node@v2
        with:
          node-version: '20.4.0'
      - name: Install deps
        run: npm ci
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test