name: Server

on:
  push:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  nest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use node
        uses: actions/setup-node@v2
        with:
          node-version: '20.4.0'
      - name: Install deps
        run: npm ci
      - name: Server start
        run: npm run start:prod
